### PR TITLE
* Removed example assets

### PR DESCRIPTION
**Pull request by BakersDozenBagels**
* Added template module & scene

### CODE REVIEW

**Comment by ZekNikZ** [comment]
Please see discussion in mod-creation starting with https://discord.com/channels/160061833166716928/201105291830493193/868919314357559319 before merging. We should consult greater modder community before implementing such a change.

**Comment by Qkrisi** [comment]
I’m sorry but I’m really against this. Examples and the assets in examples are something I and many others constantly use when creating a new mod. Having just one template module isn’t really enough. And besides, the whole point of this branch (and I don’t really see a point in a reduced branch) is to have as many features as possible to help the modder. And examples I think are really important. I’m going to leave this open for now so if people have other opinions, they can express them.

**Comment by Timwi** [comment]
> Examples and the assets in examples are something I and many others constantly use when creating a new mod.

I do not agree with your assertion that “many others _constantly_ use” those examples. Most modders who know what they’re doing either have their own cleaned-up template, or they copy an existing project (usually an earlier module they made) which is also cleaned-up. Using the modkit is bad practice and leads to git repos that are disorganized and bloated. Including the examples in the modkit encourages this bad practice. We should not be encouraging it.

Bagel’s pull request does add a template that can be used to create new modules. I’d rather we start from that and improve it than to leave the disorganized mess in it that is the current set of examples.

**Comment by Qkrisi** [comment]
Examples have been removed as a part of [95f15cc](https://github.com/Qkrisi/ktanemodkit/commit/95f15cc273c7e0dc1f1c5d65d16fbdf16d4815bd) and can now be installed from the plugin manager

**Pull request closed without merging**
